/**
 * Passive default roofing catalog definitions for FieldDive.
 *
 * These definitions do not insert rows and do not include pricing truth.
 * Future onboarding or admin flows can copy them into company-owned
 * public.catalog_items via catalogStore (not wired here).
 */

import type {
  CatalogItemDraft,
  CustomerVisibility,
  PricingBasis,
} from "@/app/lib/catalogTypes";
import { STARTER_CATALOG_COMPOSITION_ROLES } from "@/app/lib/packageCompositionIdentity";

/** Starter catalog row without company scope — cloned per company at seed time. */
export type DefaultRoofingCatalogDefinition = Omit<
  CatalogItemDraft,
  "company_id" | "active"
> & {
  metadata: { seed_key: string } & Record<string, unknown>;
};

const UNIT_PRICE: PricingBasis = "unit_price";
const FIXED_PRICE: PricingBasis = "fixed_price";
const CUSTOMER_VISIBLE: CustomerVisibility = "customer_visible";

const RAW_DEFAULT_ROOFING_CATALOG_DEFINITIONS: readonly DefaultRoofingCatalogDefinition[] =
  [
    {
      name: "Architectural shingles",
      customer_name: "Shingles",
      description: null,
      item_type: "material",
      unit: "square",
      quantity_source: "adjusted_roof_squares",
      waste_applies: true,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.architectural_shingles" },
      sort_order: 10,
    },
    {
      name: "Designer architectural shingles",
      customer_name: "Designer shingles",
      description: null,
      item_type: "material",
      unit: "square",
      quantity_source: "adjusted_roof_squares",
      waste_applies: true,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.designer_shingles" },
      sort_order: 15,
    },
    {
      name: "Synthetic underlayment",
      customer_name: "Underlayment",
      description: null,
      item_type: "material",
      unit: "square",
      quantity_source: "adjusted_roof_squares",
      waste_applies: true,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.synthetic_underlayment" },
      sort_order: 20,
    },
    {
      name: "Premium synthetic underlayment",
      customer_name: "Underlayment",
      description: null,
      item_type: "material",
      unit: "square",
      quantity_source: "adjusted_roof_squares",
      waste_applies: true,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.premium_synthetic_underlayment" },
      sort_order: 25,
    },
    {
      name: "Starter strip",
      customer_name: "Starter",
      description: null,
      item_type: "material",
      unit: "linear_foot",
      quantity_source: "starter_lf",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.starter_strip" },
      sort_order: 30,
    },
    {
      name: "Ridge cap shingles",
      customer_name: "Ridge cap",
      description: null,
      item_type: "material",
      unit: "linear_foot",
      quantity_source: "ridge_cap_lf",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.ridge_cap" },
      sort_order: 40,
    },
    {
      name: "Drip edge",
      customer_name: "Drip edge",
      description: null,
      item_type: "material",
      unit: "linear_foot",
      quantity_source: "drip_edge_lf",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.drip_edge" },
      sort_order: 50,
    },
    {
      name: "Ice & water shield (valleys)",
      customer_name: "Ice & water shield",
      description: null,
      item_type: "material",
      unit: "linear_foot",
      quantity_source: "valleys_lf",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.ice_water_valley" },
      sort_order: 60,
    },
    {
      name: "Ice & water shield (eaves)",
      customer_name: "Ice & water shield",
      description: null,
      item_type: "material",
      unit: "linear_foot",
      quantity_source: "eaves_lf",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.ice_water_eaves" },
      sort_order: 65,
    },
    {
      name: "Pipe boot",
      customer_name: "Pipe boot",
      description: null,
      item_type: "material",
      unit: "each",
      quantity_source: "pipe_boots_count",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.pipe_boot" },
      sort_order: 70,
    },
    {
      name: "Roof vent",
      customer_name: "Roof vent",
      description: null,
      item_type: "material",
      unit: "each",
      quantity_source: "vents_count",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.roof_vent" },
      sort_order: 80,
    },
    {
      name: "Step flashing",
      customer_name: "Step flashing",
      description: null,
      item_type: "material",
      unit: "linear_foot",
      quantity_source: "step_flashing_lf",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.step_flashing" },
      sort_order: 90,
    },
    {
      name: "Labor — install roofing",
      customer_name: "Roofing installation",
      description: null,
      item_type: "labor",
      unit: "square",
      quantity_source: "adjusted_roof_squares",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.install_labor" },
      sort_order: 100,
    },
    {
      name: "Labor — tear off",
      customer_name: "Tear-off",
      description: null,
      item_type: "labor",
      unit: "square",
      quantity_source: "tear_off_squares",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.tear_off_labor" },
      sort_order: 110,
    },
    {
      name: "Disposal / dump fees",
      customer_name: "Disposal",
      description: null,
      item_type: "fee",
      unit: "each",
      quantity_source: "debris_tons",
      waste_applies: false,
      pricing_basis: UNIT_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.disposal" },
      sort_order: 120,
    },
    {
      name: "Permit / administrative fee",
      customer_name: "Permit",
      description: null,
      item_type: "fee",
      unit: "fixed",
      quantity_source: "fixed",
      default_quantity: 1,
      waste_applies: false,
      pricing_basis: FIXED_PRICE,
      customer_visibility: CUSTOMER_VISIBLE,
      unit_cost_cents: null,
      unit_price_cents: null,
      labor_unit_cost_cents: null,
      metadata: { seed_key: "roofing.permit_admin_fee" },
      sort_order: 130,
    },
  ];

export const DEFAULT_ROOFING_CATALOG_DEFINITIONS: readonly DefaultRoofingCatalogDefinition[] =
  RAW_DEFAULT_ROOFING_CATALOG_DEFINITIONS.map((definition) => ({
    ...definition,
    composition_role:
      STARTER_CATALOG_COMPOSITION_ROLES[definition.metadata.seed_key] ?? null,
  }));

/**
 * Build company-scoped catalog drafts from passive defaults (no DB writes).
 */
export function buildDefaultRoofingCatalogDrafts(companyId: string): CatalogItemDraft[] {
  const scopedCompanyId = String(companyId || "").trim();
  return DEFAULT_ROOFING_CATALOG_DEFINITIONS.map((definition) => ({
    company_id: scopedCompanyId,
    name: definition.name,
    customer_name: definition.customer_name ?? null,
    description: definition.description ?? null,
    item_type: definition.item_type,
    unit: definition.unit,
    quantity_source: definition.quantity_source,
    default_quantity: definition.default_quantity ?? null,
    coverage_rate: definition.coverage_rate ?? null,
    waste_applies: definition.waste_applies ?? false,
    unit_cost_cents: null,
    unit_price_cents: null,
    labor_unit_cost_cents: null,
    pricing_basis: definition.pricing_basis,
    customer_visibility: definition.customer_visibility,
    active: true,
    sort_order: definition.sort_order ?? null,
    composition_role: definition.composition_role ?? null,
    metadata: { ...definition.metadata },
  }));
}
